name: treesequence
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.8.8
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libedit=3.1.20191231
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.10
  - python_abi=3.11
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.3.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.2.6
  - zeromq=4.3.5
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - alembic==1.14.0
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - attrs==24.2.0
      - backoff==2.2.1
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorlog==6.9.0
      - dataclasses-json==0.6.7
      - datasets==3.1.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - faiss-cpu==1.9.0
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - huggingface-hub==0.26.2
      - idna==3.10
      - jinja2==3.1.4
      - jiter==0.7.0
      - joblib==1.4.2
      - json-repair==0.30.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - langchain==0.3.7
      - langchain-community==0.3.5
      - langchain-core==0.3.15
      - langchain-openai==0.2.6
      - langchain-text-splitters==0.3.2
      - langgraph==0.2.45
      - langgraph-checkpoint==2.0.2
      - langgraph-sdk==0.1.35
      - langsmith==0.1.140
      - litellm==1.51.0
      - magicattr==0.1.6
      - mako==1.3.6
      - markupsafe==3.0.2
      - marshmallow==3.23.1
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - openai==1.54.3
      - optuna==4.0.0
      - orjson==3.10.11
      - pandas==2.2.3
      - propcache==0.2.0
      - pyarrow==18.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.6.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rpds-py==0.21.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.35
      - svgwrite==1.4.3
      - tenacity==9.0.0
      - tiktoken==0.8.0
      - tokenizers==0.20.3
      - tqdm==4.67.0
      - tskit==0.6.0
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - ujson==5.10.0
      - urllib3==2.2.3
      - xxhash==3.5.0
      - yarl==1.17.1
      - zipp==3.20.2
